# Lab 1 - The Iris Dataset

For this lab session, we will go through a simple machine learning application and create our first model. We will be using the **Iris Dataset** to create a classifier that can predict the Iris species.

## Import required modules

In [35]:
import numpy as np
import pandas as pd
import sklearn 
from sklearn.neighbors import KNeighborsClassifier
from sklearn import datasets
from sklearn.model_selection import train_test_split

## First Things First: Look at Your Data

### Question 0

Import the sklearn datasets, and then load the iris dataset, which you should assign to a variable, *iris*.

This dataset is a *Bunch* object, which is similar to a normal Python dictionary. It has keys and values. Print the keys.



In [36]:
iris = datasets.load_iris()
print(iris.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


###Question 1

You can access any value by using the key. For example, here is how to access DESCR and print it.

In [37]:
print(iris['DESCR'][:500]) # here we are just printing the first 500 characters

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= =====


print the feature names and target names

In [38]:
print("Target names:", iris['target_names'])
print("Feature names:", iris['feature_names'])

Target names: ['setosa' 'versicolor' 'virginica']
Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']



## Question 2

Assign the features (data) to X, and the target to y.

What are the *types* of X and y? (use the function, *type*)

In [39]:
x=iris['data']
y=iris['target']
print(type(x))
print(type(y))


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>




## Question 3: Examine features and target


Display the first 20 elements of X and y, using array slicing.  

In [40]:
xfirst20=x[0:20]
yfirst20=y[0:20]

print(yfirst20)
print(xfirst20)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]]


Now display the last 20 elements of X and y.

In [41]:
xlast20=x[-20:]
ylast20=y[-20:]
print(xlast20)
print(ylast20)

[[7.4 2.8 6.1 1.9]
 [7.9 3.8 6.4 2. ]
 [6.4 2.8 5.6 2.2]
 [6.3 2.8 5.1 1.5]
 [6.1 2.6 5.6 1.4]
 [7.7 3.  6.1 2.3]
 [6.3 3.4 5.6 2.4]
 [6.4 3.1 5.5 1.8]
 [6.  3.  4.8 1.8]
 [6.9 3.1 5.4 2.1]
 [6.7 3.1 5.6 2.4]
 [6.9 3.1 5.1 2.3]
 [5.8 2.7 5.1 1.9]
 [6.8 3.2 5.9 2.3]
 [6.7 3.3 5.7 2.5]
 [6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]
[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]



What is the shape of X and the shape of y?

In general, y is a 1-dimensional array, while X typically is two-dimensional. The size of the first dimension of X must be equal to the size of the single dimension of y. Use *shape* to verify that this is true.

In [42]:
print(x.shape)
print(y.shape)

(150, 4)
(150,)



## Question 4
Using `train_test_split`, split `X` and `y` into training and test sets `(X_train, X_test, y_train, and y_test)`.

(First, you need to import `train_test_split*` from `sklearn.model_selection`.)

This function should return a tuple of length 4:
`(X_train, X_test, y_train, y_test)`

Print the shape of each of these 4 elements


In [47]:
x_train, x_test, y_train, y_test = train_test_split(x,y,)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(112, 4)
(38, 4)
(112,)
(38,)


## Building Your First Model: k-Nearest Neighbors

## Question 5
Using `KNeighborsClassifier` create a classifier object using five nearest neighbors (`n_neighbors = 5`).

(First you need to import `KNeighborsClassifer` from `sklearn.neighbors`)

*This function should return a `sklearn.neighbors.classification.KNeighborsClassifier`.

In [48]:
KNN = KNeighborsClassifier(n_neighbors=5)

## Question 6

Now *fit* the model to your `X_train` and `y_train` data

In [49]:
KNN.fit(x_train,y_train)

KNeighborsClassifier()

## Evaluating the Model


## Question 7
We can measure how well the model works by using *score*, to compute accuracy.

**Use `score` to evalute the accuracy of the classifier, using the training data, and then using the test data**

In [51]:
KNN.score(x_train,y_train)

0.9732142857142857

In [52]:
KNN.score(x_test,y_test)

0.8947368421052632

## Question 8

Try creating a baseline, using DummyClassifier

(You need to import this from `sklearn.dummy`)

In [53]:
from sklearn.dummy import DummyClassifier
DC=DummyClassifier()

In [54]:
DC.fit(x_train,y_train)

DummyClassifier()

In [57]:
print(DC.score(x_train,y_train))
print(DC.score(x_test,y_test))

0.375
0.21052631578947367


## Question 9

Try some variations on the knn classifier. For example try a very large number of neighbors (what is the largest number you can use?)

Find another parameter that you can vary. Experiment to see what the best results are.

In [71]:
KNN = KNeighborsClassifier(n_neighbors=112)
KNN.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=112)

In [72]:
print(KNN.score(x_train,y_train))
print(KNN.score(x_test,y_test))

0.375
0.21052631578947367


The maximum number of neighbors cannot be above the amount of entries in an array or dataframe

In [83]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.4)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(90, 4)
(60, 4)
(90,)
(60,)


In [84]:
KNN = KNeighborsClassifier(n_neighbors=10)
KNN.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=10)

In [85]:
print(KNN.score(x_train,y_train))
print(KNN.score(x_test,y_test))

0.9777777777777777
0.9666666666666667


a test size of about 40% seems to be most accurate for this model on this dataset